modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="" # TODO
license = "MIT"

[[mods]]
modId = "fastnbt"
version = "${version}"
displayName = "FastNBT"
authors = "rdh"
description = '''

'''

[[dependencies.fastnbt]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version})"
ordering="NONE"
side="BOTH"