modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="" # TODO
license = "MIT"

[[mods]]
modId = "fes"
version = "${version}"
displayName = "FasterEntitySerialization"
authors = "rdh"
description = '''

'''

[[dependencies.fes]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version})"
ordering="NONE"
side="BOTH"