modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/rhysdh540/FasterEntitySerialization/issues"
license = "MIT"

[[mods]]
modId = "fes"
version = "${version}"
displayName = "FasterEntitySerialization"
authors = "rdh"
description = "Speeds up the serialization of entities by only converting necessary keys to NBT"

[[dependencies.fes]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version})"
ordering="NONE"
side="BOTH"